#!/bin/sh

export XPRESSDIR=/opt/xpressmp
export PATH=$XPRESSDIR/bin:$PATH
export LD_LIBRARY_PATH=$XPRESSDIR/lib:$LD_LIBRARY_PATH
export CLASSPATH=$XPRESSDIR/lib/xprs.jar:$CLASSPATH
export CLASSPATH=$XPRESSDIR/lib/xprb.jar:$CLASSPATH
export CLASSPATH=$XPRESSDIR/lib/xprm.jar:$CLASSPATH
export XPRESS=$XPRESSDIR/bin
