#!/usr/bin/env python3

import sys, os, subprocess


def main(inp, out):

	alg = ['mcndp/raw', 'mcndp/cg']

	for element in sorted(os.listdir(inp)):
		inppath = os.path.abspath(os.path.join(inp, element))
		if os.path.isfile(inppath):
			for a in alg:
				outpath = os.path.abspath(os.path.join(out, a, element))
				os.makedirs(outpath)
				subprocess.call(['./run', a, '<', inppath, '>', outpath])


if __name__ == '__main__':
	main(*sys.argv[1:])